blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.blog_list, name='blog_list'),
    path('<int:pk>', views.blog_detail, name='blog_detail'),
    path('new', views.blog_new, name='blog_new'),
    path('edit/<int:pk>', views.blog_edit, name='blog_edit'),
    path('delete/<int:pk>', views.blog_delete, name='blog_delete'),
    path('<slug:slug>', views.post_detail, name='post_detail'),
    path('upload/', views.image_upload_view)
]

#from corey:
'''from django.urls import path
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView
)
from . import views

urlpatterns = [
    path('', PostListView.as_view(), name='blog-home'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('about/', views.about, name='blog-about'),
]'''

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

static_patterns = static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

urlpatterns = [
    path('', include('blog.urls')),
    path('accounts/', include('allauth.urls')),
    path('my_backend/', admin.site.urls),
] + static_patterns

#if settings.DEBUG:
    #urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#corey:
'''from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', include('blog.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)'''

mysite/templates/base.html
{% load static %}
{% load bootstrap4 %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    {% bootstrap_css %}
    <link href="{% static 'css/main.css' %}" rel="stylesheet" type="text/css" />

    {% if title %}
      <title>Django Blog - {{ title }}</title>
    {% else %}
      <title>Django Blog</title>
    {% endif %}
</head>
<body>
    {% bootstrap_messages %}

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">My Django Blog 2</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'blog:blog_list' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'account_email' %}">Change E-mail</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'account_login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'account_signup' %}">Signup</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    {% block content %}{% endblock %}

    <footer>
        <div id="footerTest">
            Made with wubb by Sarah
        </div>
    </footer>

    {% bootstrap_javascript jquery='full' %}
    <script src="//cdn.muicss.com/mui-0.10.1/js/mui.min.js"></script>
    <script src="{% static 'js/script.js' %}"></script>

</body>
</html>