blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.blog_list, name='blog_list'),
    path('<int:pk>', views.blog_detail, name='blog_detail'),
    path('new', views.blog_new, name='blog_new'),
    path('edit/<int:pk>', views.blog_edit, name='blog_edit'),
    path('delete/<int:pk>', views.blog_delete, name='blog_delete'),
    path('<slug:slug>', views.post_detail, name='post_detail'),
    path('upload/', views.image_upload_view)
]

#from corey:
'''from django.urls import path
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView
)
from . import views

urlpatterns = [
    path('', PostListView.as_view(), name='blog-home'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('about/', views.about, name='blog-about'),
]'''

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

static_patterns = static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

urlpatterns = [
    path('', include('blog.urls')),
    path('accounts/', include('allauth.urls')),
    path('my_backend/', admin.site.urls),
] + static_patterns

#if settings.DEBUG:
    #urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#corey:
'''from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', include('blog.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)'''

blog/models.py
from django.db import models
from django.conf import settings

STATUS = (
    (0, "Draft"),
    (1, "Publish")
)


class Tag(models.Model):
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name


class Blog(models.Model):
    title = models.CharField(max_length=100, unique=True)
    post = models.TextField()
    slug = models.SlugField(max_length=50)
    added = models.DateTimeField(auto_now_add=True)
    edited = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE,
                             null=True, blank=True)
    status = models.CharField(max_length=1, choices=STATUS, default=0)
    tags = models.ManyToManyField(Tag, related_name='tags')

    def __str__(self):
        return self.slug

    class Meta:
        ordering = ['-added']


class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name="comments")
    name = models.CharField(max_length=80)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)


class Image(models.Model):
    image = models.ImageField(upload_to='images/', blank = True, null=True)
    # TODO: upload image to cloud / S3
    url = models.URLField(blank=True, null=True)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        if self.url:
            # then it's on S3
            return self.url
        # it's local
        return self.image.url

#corey

'''from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title'''

blog/forms.py
from django.forms import ModelForm

from .models import Blog, Comment, Image


class BlogForm(ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'post']


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'body')


class ImageForm(ModelForm):
    class Meta:
        model = Image
        fields = ('image',)

blog/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect
from django.utils.text import slugify

from .models import Blog, Comment, Image
from .forms import BlogForm, CommentForm, ImageForm


def blog_list(request):
    posts = Blog.objects.all()
    return render(request, 'blog/list.html', {'posts': posts})


def blog_detail(request, pk):
    post = get_object_or_404(Blog, pk=pk)
    form = ImageForm(request.POST or None, request.FILES)
    context = {'post': post, 'blog_form': blog_form}
    return render(request, 'blog/detail.html', context)


@login_required
def blog_new(request):
    blog_form = BlogForm(request.POST or None)
    image_form = ImageForm(request.POST or None, request.FILES)

    if blog_form.is_valid() and image_form.is_valid():
        blog = blog_form.save(commit=False)
        blog.slug = slugify(blog.title)
        blog.user = request.user
        blog.save()

        # TODO: this needs to be multiple images
        im = image_form.save(commit=False)
        im.blog = blog
        im.save()

        messages.success(request, 'Added post')
        return redirect('blog:blog_list')

    context = {'blog_form': blog_form, 'image_form': image_form}
    return render(request, 'blog/form.html', context)


@login_required
def blog_edit(request, pk):
    # Nth time around / editing, check if owner is accessing
    post = get_object_or_404(Blog, pk=pk, user=request.user)
    blog_form = BlogForm(request.POST or None, instance=post)
    image_form = ImageForm(request.POST or None, request.FILES)
    if blog_form.is_valid() and image_form.is_valid():
        blog_post = blog_form.save()

        # delete previous images
        Image.objects.filter(blog=blog_post).delete()

        img = image_form.save(commit=False)
        img.blog = blog_post
        img.save()

        messages.success(request, 'Updated post')
        return redirect('blog:blog_list')

    return render(request, 'blog/form.html', {'post': post,
                                              'blog_form': blog_form,
                                              'image_form': image_form})


@login_required
def blog_delete(request, pk):
    # Nth time around / editing, check if owner is accessing
    post = get_object_or_404(Blog, pk=pk, user=request.user)
    if request.method == 'POST':
        post.delete()
        messages.success(request, 'Deleted post')
        return redirect('blog:blog_list')

    return render(request, 'blog/delete.html', {'post': post})


@login_required
def post_detail(request, slug):
    template_name = 'post_detail.html'
    blog = get_object_or_404(Blog, slug=slug)
    images = blog.image_set.all()

    # List of active comments for this post
    new_comment = None

    comment_form = CommentForm(request.POST or None)

    if request.method == 'POST':
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.blog = blog
            new_comment.author = request.user
            new_comment.save()

    comments = blog.comments.filter(active=True)

    return render(request,
                    'blog/post_detail.html',
                    {'blog': blog,
                    'images': images,
                    'comments': comments,
                    'comment_form': comment_form})


def image_upload_view(request):
    """Process images uploaded by users"""
    if request.method == 'POST':
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            # Get the current instance object to display in the template
            img_obj = form.instance
            return render(request, 'index.html', {'form': form, 'img_obj': img_obj})
    else:
        form = ImageForm()
    return render(request, 'index.html', {'form': form})

blog/templates/blog/about.html
{% extends "base.html" %}
{% block content %}
    <h1>About Page</h1>
{% endblock content %}

blog/templates/blog/delete.html
{% extends 'base.html' %}

{% block content %}

    <h1>Confirm Delete Post</h1>

    <form method="post">
        {% csrf_token %}
        <h2>{{ post.title }}</h2>
        <p>Are you sure you want to delete this post?</p>
        <input type="submit" value="Delete" class="btn btn-danger">
        <a href="{% url "blog:blog_list" %}" class="btn btn-outline-dark">Go Back</a>
    </form>

{% endblock %}

blog/templates/blog/edit.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}

    <h1>{% if post %}Edit{% else %}New{% endif %} Post</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {% bootstrap_form blog_form %}

        {% if image.image.url %}
            <img style="width: 400px;" src="{{ post.image_set.first.image.url }}" alt="post cover">
        {% endif %}

        {% bootstrap_form image_form %}

        <input type="submit" value="{%if post %}Edit{% else %}New{% endif %}" />
        <a href="{%url "blog:blog_list" %}">Go Back</a>
    </form>

{% endblock %}

blog/templates/blog/form.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}

    <h1>{% if post %}Edit{% else %}New{% endif %} Post</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {% bootstrap_form blog_form %}

        {% if image.image.url %}
            <img style="width: 400px;" src="{{ post.image_set.first.image.url }}" alt="post cover">
        {% endif %}

        {% bootstrap_form image_form %}

        <input type="submit" value="{% if post %}Edit{% else %}New{% endif %}" />
        <a href="{% url "blog:blog_list" %}">Go Back</a>
    </form>

{% endblock %}

blog/templates/blog/index.html
{% extends "base.html" %}
{% block content %}
    {% for post in posts %}
        <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="#">{{ post.author }}</a>
              <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
            </div>
            <h2><a class="article-title" href="#">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
{% endblock content %}

blog/templates/blog/list.html
{% extends 'base.html' %}

{% block content %}

  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Slug</th>
        <th>Post</th>
        <th>Cover</th>
        <th>Author</th>
        {% if user.is_authenticated %}
          <th colespan="2">Edit Post</th>
        {% endif %}
      </tr>
    </thead>
    <tbody>
      {% for post in posts %}
        <tr>
            <td><a href="{% url "blog:post_detail" post.slug %}">{{post.title }}</a></td>
            <td>{{ post.slug }}</td>
            <td>{{ post.post }}</td>
            {% if image.image.url %}
                <td><img style="width: 400px;" src="{{ post.image_set.first.image.url }}" alt="post cover"></td>
            {% endif %}
            <td>{{ post.user.username }}</td>
            {% if user.is_authenticated and post.user == user %}
              <td><a href="{% url "blog:blog_edit" post.id %}" class="btn btn-outline-warning">Edit</a></td>
              <td><a href="{% url "blog:blog_delete" post.id %}" class="btn btn-outline-danger">Delete</a></td>
            {% endif %}
        </tr>
      {% endfor %}
    </tbody>
  </table>

  {% if user.is_authenticated %}
    <div>
      <a href="{% url "blog:blog_new" %}" class="btn btn-primary">Add a post</a>
    </div>
  {% endif %}

{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">
        <h1>{% block title %} {{ blog.title }} {% endblock title %}</h1>
        <p class=" text-muted">{{ blog.user.username }} | {{ blog.added|timesince }} ago</p>
        <p class="card-text ">{{ blog.post | safe }}
        {% for image in images %}
          {% if image.image.url %}
            <img src="{{ image.image.url }}" alt="image for {{ blog.title }}">
          {% endif %}
        {% endfor %}
        </p>
      </div>
    </div>

    <div class="col-md-8 card mb-4  mt-3 ">
      <div class="card-body">
        <!-- comments -->
        <h2>{{ comments.count }} comments</h2>

        {% for comment in comments %}
        <div class="comments" style="padding: 10px;">
          <p class="font-weight-bold">
            {{ comment.name }}
            <span class=" text-muted font-weight-normal">
              {{ comment.created|timesince }}
            </span>
          </p>
          {{ comment.body | linebreaks }}
        </div>
        {% endfor %}
      </div>
    </div>
    <div class="col-md-8 card mb-4  mt-3 ">

      <div class="card-body">
        <h3>Leave a comment</h3>
        <form method="post" style="margin-top: 1.3em;">
          {{ comment_form.as_p }}
          {% csrf_token %}
          <button type="submit" class="btn btn-primary  btn-lg">Submit</button>
        </form>
      </div>

    </div>
  </div>
</div>
{% endblock content %}